version: '3.1'

services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGES_DB=gym_manager
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    container_name: gym_manager_database
  api:
    container_name: gym_manager_api
    depends_on:
      - db
    image: missshevel/gym_manager_api:latest
    command: yarn start:prod
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=production
      - DB_HOST=gym_manager_database
      - PORT=4000
      - DB_PORT=5432
  client:
    container_name: gym_manager_client
    depends_on:
      - api
    image: missshevel/gym_manager_client:latest
    command: yarn start
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production

volumes:
  db:
    driver: local
