version: '3.1'

services:
  db:
    image: postgres:14.1-alpine
    container_name: dyploma_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '54320:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
