name: Deploy

on:
  push:
    branches: [dev]

jobs:
  backend_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_USER}}/gym_manager_api:latest .
      - name: Login to docker hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Push to docker hub
        run: docker push ${{secrets.DOCKER_USER}}/gym_manager_api:latest

  client_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_USER}}/gym_manager_client:latest .
      - name: Login to docker hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Push to docker hub
        run: docker push ${{secrets.DOCKER_USER}}/gym_manager_client:latest